export const SECCESS_LOGEDIN = "SECCESS_LOGEDIN";
export const SECCESS_RELOAD_LOGEDIN = "SECCESS_RELOAD_LOGEDIN";
export const SECCESS_SINGNUP = "SECCESS_SINGNUP";
export const LOGOUT_USER = "LOGOUT_USER";

export const FEILD_LOGEDIN = "FEILD_LOGEDIN";

export const START_LOADER = "START_LOADER";
